name: 💡 Ideas & Suggestions
description: Share ideas for improving the project
title: "[Idea] "
labels: ["idea", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! We love hearing from the community about how to make this project better.
  - type: textarea
    id: idea-description
    attributes:
      label: What's your idea?
      description: Describe your idea or suggestion
      placeholder: Explain your idea in detail...
    validations:
      required: true
  - type: textarea
    id: problem-solved
    attributes:
      label: What problem does this solve?
      description: What issue or limitation would this idea address?
      placeholder: Describe the problem or limitation this idea would solve...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: Describe your vision for how this could work...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: Describe any alternative solutions you've thought about...
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Links, examples, mockups, etc.
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By participating in this discussion, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct
          required: true
